#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");

const tokens = JSON.parse(
  readFileSync(join(__dirname, "tokens.json"), "utf-8"),
);

const webOut = join(
  REPO_ROOT,
  "web",
  "frontend",
  "src",
  "design",
  "tokens.ts",
);
const webCssOut = join(
  REPO_ROOT,
  "web",
  "frontend",
  "src",
  "design",
  "tokens.css",
);
const mobileOut = join(REPO_ROOT, "mobile", "lib", "core", "design", "tokens.dart");

mkdirSync(dirname(webOut), { recursive: true });
mkdirSync(dirname(mobileOut), { recursive: true });

writeFileSync(webOut, generateTs(tokens));
writeFileSync(webCssOut, generateCss(tokens));
writeFileSync(mobileOut, generateDart(tokens));

console.log("✓ design/tokens.json → web/frontend/src/design/tokens.ts");
console.log("✓ design/tokens.json → web/frontend/src/design/tokens.css");
console.log("✓ design/tokens.json → mobile/lib/core/design/tokens.dart");

function generateTs(tokens) {
  const json = JSON.stringify(tokens, null, 2);
  return `// AUTO-GENERATED by design/build.mjs — do not edit by hand.
// Edit design/tokens.json then run \`npm run design:build\` from web/frontend.

export const tokens = ${json} as const;

export const colors = tokens.colors;
`;
}

function generateCss(tokens) {
  const lines = [];
  for (const [groupName, groupValue] of Object.entries(tokens.colors)) {
    if (typeof groupValue === "string") {
      lines.push(`  --color-${kebab(groupName)}: ${groupValue};`);
    } else {
      for (const [variantName, hex] of Object.entries(groupValue)) {
        lines.push(
          `  --color-${kebab(groupName)}-${kebab(variantName)}: ${hex};`,
        );
      }
    }
  }
  return `/* AUTO-GENERATED by design/build.mjs — do not edit by hand. */
/* Edit design/tokens.json then run \`npm run design:build\` from web/frontend. */

@theme {
${lines.join("\n")}
}
`;
}

function kebab(s) {
  return s.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase();
}

function generateDart(tokens) {
  const lines = [];
  for (const [groupName, groupValue] of Object.entries(tokens.colors)) {
    if (typeof groupValue === "string") {
      lines.push(
        `  static const ${camel(groupName)} = ${dartColor(groupValue)};`,
      );
    } else {
      for (const [variantName, hex] of Object.entries(groupValue)) {
        lines.push(
          `  static const ${camel(groupName)}${pascal(variantName)} = ${dartColor(hex)};`,
        );
      }
    }
  }
  return `// AUTO-GENERATED by design/build.mjs — do not edit by hand.
// Edit design/tokens.json then run \`npm run design:build\` from web/frontend.

import 'package:flutter/material.dart';

class AppColors {
${lines.join("\n")}
}
`;
}

function dartColor(hex) {
  const clean = hex.replace("#", "").toUpperCase();
  return `Color(0xFF${clean})`;
}

function camel(s) {
  return s[0].toLowerCase() + s.slice(1);
}

function pascal(s) {
  return s[0].toUpperCase() + s.slice(1);
}
