// AUTO-GENERATED by design/build.mjs — do not edit by hand.
// Edit design/tokens.json then run `npm run design:build` from web/frontend.

import 'package:flutter/material.dart';

class AppColors {
  static const purpleDark = Color(0xFF6D0094);
  static const purplePrimary = Color(0xFF810CA8);
  static const purpleTertiary = Color(0xFFE5B8F4);
  static const purpleGradientTop = Color(0xFFC147E9);
  static const purpleGradientBottom = Color(0xFF2D033B);
  static const greyDark = Color(0xFF50555C);
  static const greyMedium = Color(0xFF667085);
  static const greyLighter = Color(0xFFF9FAFB);
  static const yellowPrimary = Color(0xFFFFBD24);
  static const yellowGradientTop = Color(0xFFFABD05);
  static const yellowGradientBottom = Color(0xFFFA8905);
  static const redError = Color(0xFFFF3B30);
  static const labelSecondaryDark = Color(0xFFEBEBF5);
  static const background = Color(0xFFF9F9F9);
  static const white = Color(0xFFFFFFFF);
}
