// AUTO-GENERATED by design/build.mjs — do not edit by hand.
// Edit design/tokens.json then run `npm run design:build` from web/frontend.

export const tokens = {
  "colors": {
    "purple": {
      "dark": "#6D0094",
      "primary": "#810CA8",
      "tertiary": "#E5B8F4",
      "gradientTop": "#C147E9",
      "gradientBottom": "#2D033B"
    },
    "grey": {
      "dark": "#50555C",
      "medium": "#667085",
      "lighter": "#F9FAFB"
    },
    "yellow": {
      "primary": "#FFBD24",
      "gradientTop": "#FABD05",
      "gradientBottom": "#FA8905"
    },
    "red": {
      "error": "#FF3B30"
    },
    "label": {
      "secondaryDark": "#EBEBF5"
    },
    "background": "#F9F9F9",
    "white": "#FFFFFF"
  }
} as const;

export const colors = tokens.colors;
